// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct Vote0Data {
  uint8 voteForPlayer1;
  uint8 voteForPlayer2;
  uint8 voteForPlayer3;
}

library Vote0 {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "voteforbot", name: "Vote0", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462766f7465666f72626f7400000000566f7465300000000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0003030001010100000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint8, uint8, uint8)
  Schema constant _valueSchema = Schema.wrap(0x0003030000000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "matchEntity";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "voteForPlayer1";
    fieldNames[1] = "voteForPlayer2";
    fieldNames[2] = "voteForPlayer3";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get voteForPlayer1.
   */
  function getVoteForPlayer1(bytes32 matchEntity) internal view returns (uint8 voteForPlayer1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get voteForPlayer1.
   */
  function _getVoteForPlayer1(bytes32 matchEntity) internal view returns (uint8 voteForPlayer1) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set voteForPlayer1.
   */
  function setVoteForPlayer1(bytes32 matchEntity, uint8 voteForPlayer1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((voteForPlayer1)), _fieldLayout);
  }

  /**
   * @notice Set voteForPlayer1.
   */
  function _setVoteForPlayer1(bytes32 matchEntity, uint8 voteForPlayer1) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((voteForPlayer1)), _fieldLayout);
  }

  /**
   * @notice Get voteForPlayer2.
   */
  function getVoteForPlayer2(bytes32 matchEntity) internal view returns (uint8 voteForPlayer2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get voteForPlayer2.
   */
  function _getVoteForPlayer2(bytes32 matchEntity) internal view returns (uint8 voteForPlayer2) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set voteForPlayer2.
   */
  function setVoteForPlayer2(bytes32 matchEntity, uint8 voteForPlayer2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((voteForPlayer2)), _fieldLayout);
  }

  /**
   * @notice Set voteForPlayer2.
   */
  function _setVoteForPlayer2(bytes32 matchEntity, uint8 voteForPlayer2) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((voteForPlayer2)), _fieldLayout);
  }

  /**
   * @notice Get voteForPlayer3.
   */
  function getVoteForPlayer3(bytes32 matchEntity) internal view returns (uint8 voteForPlayer3) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get voteForPlayer3.
   */
  function _getVoteForPlayer3(bytes32 matchEntity) internal view returns (uint8 voteForPlayer3) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set voteForPlayer3.
   */
  function setVoteForPlayer3(bytes32 matchEntity, uint8 voteForPlayer3) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((voteForPlayer3)), _fieldLayout);
  }

  /**
   * @notice Set voteForPlayer3.
   */
  function _setVoteForPlayer3(bytes32 matchEntity, uint8 voteForPlayer3) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((voteForPlayer3)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 matchEntity) internal view returns (Vote0Data memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 matchEntity) internal view returns (Vote0Data memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 matchEntity, uint8 voteForPlayer1, uint8 voteForPlayer2, uint8 voteForPlayer3) internal {
    bytes memory _staticData = encodeStatic(voteForPlayer1, voteForPlayer2, voteForPlayer3);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 matchEntity, uint8 voteForPlayer1, uint8 voteForPlayer2, uint8 voteForPlayer3) internal {
    bytes memory _staticData = encodeStatic(voteForPlayer1, voteForPlayer2, voteForPlayer3);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 matchEntity, Vote0Data memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.voteForPlayer1, _table.voteForPlayer2, _table.voteForPlayer3);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 matchEntity, Vote0Data memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.voteForPlayer1, _table.voteForPlayer2, _table.voteForPlayer3);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint8 voteForPlayer1, uint8 voteForPlayer2, uint8 voteForPlayer3) {
    voteForPlayer1 = (uint8(Bytes.getBytes1(_blob, 0)));

    voteForPlayer2 = (uint8(Bytes.getBytes1(_blob, 1)));

    voteForPlayer3 = (uint8(Bytes.getBytes1(_blob, 2)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (Vote0Data memory _table) {
    (_table.voteForPlayer1, _table.voteForPlayer2, _table.voteForPlayer3) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 matchEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 matchEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint8 voteForPlayer1,
    uint8 voteForPlayer2,
    uint8 voteForPlayer3
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(voteForPlayer1, voteForPlayer2, voteForPlayer3);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint8 voteForPlayer1,
    uint8 voteForPlayer2,
    uint8 voteForPlayer3
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(voteForPlayer1, voteForPlayer2, voteForPlayer3);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 matchEntity) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = matchEntity;

    return _keyTuple;
  }
}
