// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Vote0, Vote0Data } from "./tables/Vote0.sol";
import { Vote1, Vote1Data } from "./tables/Vote1.sol";
import { BotMatch, BotMatchData } from "./tables/BotMatch.sol";
import { Counter } from "./tables/Counter.sol";
