// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Vote, VoteData } from "./tables/Vote.sol";
import { BotMatch, BotMatchData } from "./tables/BotMatch.sol";
import { Counter } from "./tables/Counter.sol";
