// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBotActionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBotActionSystem {
  error BotNotInMatch();
  error MatchAlreadyFinished();

  function voteforbot__joinMatch(bytes32 matchEntity, uint256 spawnIndexToStartFrom, bytes32 heroChoice) external;

  function voteforbot__init(bytes32 matchEntity, bytes32 factoryEntity) external;

  function voteforbot__process(bytes32 matchEntity) external;

  function voteforbot__vote(bytes32 matchEntity, uint8 voteIndex) external;

  function voteforbot__forceVoteNow(bytes32 matchEntity, uint8 voteIndex) external;

  function voteforbot__getFactories(bytes32 matchEntity) external view returns (bytes32[] memory);

  function voteforbot__getGold(bytes32 matchEntity) external returns (int32 gold);

  function voteforbot__getTemplateIds(
    bytes32 matchEntity,
    bytes32 factoryEntity
  ) external view returns (bytes32[] memory);

  function voteforbot__getFactoryPosition(
    bytes32 matchEntity,
    bytes32 factoryEntity
  ) external view returns (int32 x, int32 y);

  function voteforbot__build(bytes32 matchEntity, bytes32 factoryEntity, bytes32 templateId, int32 x, int32 y) external;
}
