// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBotActionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBotActionSystem {
  function voteforbot__joinMatch(bytes32 matchEntity) external;

  function voteforbot__acceptOrbPayment() external;

  function voteforbot__withdrawbeforeMatchGetCreated() external;

  function voteforbot__createMatch() external;

  function voteforbot__process(
    bytes32 matchEntity,
    bytes32[] memory factoryEntities,
    bytes32[] memory unitEntities
  ) external;
}
